spring.application.name=smartslot

application.generic.text=Generic Text for Dev Application Props

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/smartslot-dev
spring.datasource.username=postgres
spring.datasource.password=dbuser
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true